import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function PlanningSchedulingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
